// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","file":"@/pages/User/Login/index.tsx","parentId":"1","id":"2"},"3":{"file":"@/pages/404.tsx","parentId":"1","id":"3"},"4":{"path":"/welcome","name":"welcome","icon":"smile","file":"@/pages/Welcome.tsx","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/configsite","name":"Danh Sách Website","icon":"crown","file":"@/pages/configsite/index.tsx","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/admin","name":"admin","icon":"crown","access":"canAdmin","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/admin/sub-page","name":"sub-page","icon":"smile","file":"@/pages/Welcome.tsx","parentId":"6","id":"7"},"8":{"file":"@/pages/404.tsx","parentId":"6","id":"8"},"9":{"name":"list.table-list","icon":"table","path":"/list","file":"@/pages/TableList/index.tsx","parentId":"ant-design-pro-layout","id":"9"},"10":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"10"},"11":{"file":"@/pages/404.tsx","parentId":"ant-design-pro-layout","id":"11"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","file":"@/.umi/plugin-layout/Layout.tsx","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi","file":"/Users/kevinpham/Projects/nodejs-allwoocommerce/myapp/src/.umi/plugin-openapi/openapi.tsx"}},
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__configsite__index" */'@/pages/configsite/index.tsx')),
'6': React.lazy(() => import( './EmptyRoute')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'10': React.lazy(() => import( './EmptyRoute')),
'11': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: ".umi__plugin-layout__Layout" */'@/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: ".umi__plugin-openapi__openapi" */'/Users/kevinpham/Projects/nodejs-allwoocommerce/myapp/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
